# Team-player dictionary
players_by_team = {
    "Celtics": [
        ("Jayson Tatum"),
        ("Jaylen Brown"),
        ("Derrick White"),
        ("Jrue Holiday"),
        ("Payton Pritchard"),
        ("Kristaps Porzingis")
    ],
    "Knicks": [
        ("Karl-Anthony Towns"),
        ("Jalen Brunson"),
        ("OG Anunoby"),
        ("Mikal Bridges"),
        ("Josh Hart"),
        ("Miles McBride")
    ],
    "Cavs": [
        ("Donovan Mitchell"),
        ("Darius Garland"),
        ("Evan Mobley"),
        ("Jarrett Allen"),
        ("Dean Wade"),
        ("Max Strus"),
        ("De'Andre Hunter"),
        ("Ty Jerome"),
    ],
    #"Bucks": [
        #("Damian Lillard"),
        #("Andre Jackson Jr"),
        #("Taurean Prince"),
        #("Giannis Antetokounmpo"),
        #("Brook Lopez"),
        #("Gary Trent Jr")
    #],
    #"Pacers": [
        #("Tyrese Haliburton"),
        #("Myles Turner"),
        #("Pascal Siakam"),
        #("Bennedict Mathurin"),
        #("T.J. McConnell"),
        #("Andrew Nembhard"),
        #("Ben Sheppard"),
        #("Obi Toppin"),
        #("Aaron Nesmith"),
    #],
    "Pistons": [
        ("Cade Cunningham"),
        ("Tim Hardaway Jr"),
        ("Ausar Thompson"),
        ("Tobias Harris"),
        ("Malik Beasley"),
        ("Jalen Duren"),
        ("Dennis Schroder"),
        ("Isaiah Stewart"),
    ],
    "Magic": [
        ("Cole Anthony"),
        ("Kentavious Caldwell-Pope"),
        ("Franz Wagner"),
        ("Paolo Banchero"),
        ("Goga Bitadze"),
        ("Wendell Carter Jr")
    ],
    "Heat": [
        ("Tyler Herro"),
        ("Duncan Robinson"),
        ("Andrew Wiggins"),
        ("Bam Adebayo"),
        ("Kel'el Ware"),
        ("Terry Rozier"),
        ("Jaime Jaquez Jr"),
        ("Davion Mitchell"),
    ],
    "Thunder": [
        ("Shai Gilgeous-Alexander"),
        ("Jalen Williams"),
        ("Isaiah Joe"),
        ("Luguentz Dort"),
        ("Isaiah Hartenstein"),
        ("Aaron Wiggins"),
        ("Cason Wallace"),
        ("Chet Holmgren"),
    ],
    "Nuggets": [
        ("Nikola Jokic"),
        ("Jamal Murray"),
        ("Michael Porter Jr"),
        ("Christian Braun"),
        ("Aaron Gordon"),
        ("Russell Westbrook"),
        ("Julian Strawther")
    ],
    "Timberwolves": [
        ("Anthony Edwards"),
        ("Julius Randle"),
        ("Jaden McDaniels"),
        ("Rudy Gobert"),
        ("Mike Conley"),
        ("Donte DiVincenzo"),
        ("Naz Reid"),
        ("Nickeil Alexander-Walker")
    ],
    "Warriors": [
        ("Stephen Curry"),
        ("Buddy Hield"),
        ("Draymond Green"),
        ("Jimmy Butler"),
        ("Jonathan Kuminga"),
        ("Brandin Podziemski"),
        ("Quinten Post")
    ],
    "Clippers": [
        ("James Harden"),
        ("Ivica Zubac"),
        ("Norman Powell"),
        ("Derrick Jones Jr"),
        ("Kevin Porter Jr"),
        ("Kris Dunn"),
        ("Amir Coffey"),
        ("Bogdan Bogdanovic"),
        
    ],
    "Lakers": [
        ("Luka Doncic"),
        ("LeBron James"),
        ("Austin Reaves"),
        ("Rui Hachimura"),
        ("Jaxson Hayes"),
        ("Dorian Finney-Smith")
    ],
    "Rockets": [
        ("Jalen Green"),
        ("Alperen Sengun"),
        ("Fred VanVleet"),
        ("Dillon Brooks"),
        ("Jabari Smith Jr"),
        ("Amen Thompson")
    ],
    "Grizzlies": [
        ("Jaren Jackson Jr"),
        ("Ja Morant"),
        ("Santi Aldama"),
        ("Desmond Bane"),
        ("Zach Edey"),
        ("Jaylen Wells"),
        ("Scotty Pippen Jr."),
        ("Luke Kennard")
    ],
}

# Team-player dictionary
top_players = {
    "ppg":[
        ("1", "Shai Gilgeous-Alexander", "32.2"),
        ("2", "Giannis Antetokounmpo", "31.2"),
        ("3", "Nikola Jokić", "29.4"),
        ("4", "Anthony Edwards", "27.6"),
        ("5", "Tyrese Maxey", "27.4"),
        ("6", "Kevin Durant", "27.2"),
        ("7", "Jayson Tatum", "26.8"),
        ("8", "Devin Booker", "26"),
        ("9", "Jalen Brunson", "26"),
        ("10", "Anthony Davis", "25.7"),
        ("11", "Damian Lillard", "25.5"),
        ("12", "Cade Cunningham", "25.4"),
        ("13", "Kyrie Irving", "24.9"),
        ("14", "Karl-Anthony Towns", "24.8"),
        ("15", "De'Aaron Fox", "24.7"),
        ("16", "LeBron James", "24.7"),
        ("17", "Victor Wembanyama", "24.3"),
        ("18", "Norman Powell", "24.2"),
        ("19", "Donovan Mitchell", "24"),
        ("20", "Trae Young", "24"),
        ("21", "Tyler Herro", "23.9"),
        ("22", "Zach LaVine", "23.4"),
        ("23", "Stephen Curry", "23.4"),
        ("24", "Jaylen Brown", "22.9"),
        ("25", "Jaren Jackson Jr.", "22.8"),
        ("26", "CJ McCollum", "22.4"),
        ("27", "Trey Murphy III", "22.4"),
        ("28", "DeMar DeRozan", "22.1"),
        ("29", "RJ Barrett", "21.9"),
        ("30", "James Harden", "21.5"),
        ("31", "Jalen Green", "21.5"),
        ("32", "Darius Garland", "21.3"),
        ("33", "Jamal Murray", "21.2"),
        ("34", "Jordan Poole", "21"),
        ("35", "Jalen Williams", "20.9"),
        ("36", "Pascal Siakam", "20.6"),
        ("37", "Domantas Sabonis", "20.3"),
        ("38", "Miles Bridges", "20.1"),
        ("39", "Scottie Barnes", "19.9"),
        ("40", "Lauri Markkanen", "19.3"),
        ("41", "Austin Reaves", "19.2"),
        ("42", "Cameron Johnson", "19.1"),
        ("43", "Nikola Vučević", "19.1"),
        ("44", "Alperen Şengün", "19"),
        ("45", "Julius Randle", "18.9"),
        ("46", "Michael Porter Jr.", "18.6"),
        ("47", "Evan Mobley", "18.6"),
        ("48", "Anfernee Simons", "18.5"),
        ("49", "De'Andre Hunter", "18.5"),
        ("50", "Collin Sexton", "18.3"),
        ("51", "Desmond Bane", "18.2"),
        ("52", "Coby White", "18.1"),
        ("53", "Malik Monk", "18"),
        ("54", "Tyrese Haliburton", "17.9"),
        ("55", "Mikal Bridges", "17.6"),
        ("56", "Andrew Wiggins", "17.5"),
        ("57", "Shaedon Sharpe", "17"),
        ("58", "Keyonte George", "16.8"),
        ("59", "Bam Adebayo", "16.8"),
        ("60", "Bennedict Mathurin", "16.6"),
        ("61", "Malik Beasley", "16.5"),
        ("62", "OG Anunoby", "16.1"),
        ("63", "Derrick White", "16.1"),
        ("64", "Devin Vassell", "15.6"),
        ("65", "Ivica Zubac", "15.3"),
        ("66", "Myles Turner", "15.1"),
        ("67", "Gradey Dick", "14.9"),
        ("68", "Christian Braun", "14.8"),
        ("69", "Deni Avdija", "14.8"),
        ("70", "Josh Hart", "14.7"),
        ("71", "Fred VanVleet", "14.6"),
        ("72", "Naz Reid", "14.6"),
        ("73", "Kelly Oubre Jr.", "14.5"),
        ("74", "P.J. Washington", "14.5"),
        ("75", "Jerami Grant", "14.3"),
        ("76", "Jakob Poeltl", "14.2"),
        ("77", "Payton Pritchard", "14.1"),
        ("78", "Amen Thompson", "13.9"),
        ("79", "Klay Thompson", "13.8"),
        ("80", "Dennis Schröder", "13.8"),
        ("81", "Dyson Daniels", "13.8"),
        ("82", "Bobby Portis", "13.7"),
        ("83", "Tobias Harris", "13.6"),
        ("84", "Jarrett Allen", "13.6"),
        ("85", "Rui Hachimura", "13.4"),
        ("86", "Dillon Brooks", "13.4"),
        ("87", "Russell Westbrook", "13"),
        ("88", "D'Angelo Russell", "12.9"),
        ("89", "Stephon Castle", "12.8"),
        ("90", "Santi Aldama", "12.7"),
        ("91", "Josh Giddey", "12.7"),
        ("92", "Scoot Henderson", "12.4"),
        ("93", "Brook Lopez", "12.4"),
        ("94", "Ayo Dosunmu", "12.3"),
        ("95", "Bilal Coulibaly", "12.3"),
        ("96", "Daniel Gafford", "12.3"),
        ("97", "Terry Rozier", "12.2"),
        ("98", "Onyeka Okongwu", "12.1"),
        ("99", "Keegan Murray", "12"),
        ("100", "Keldon Johnson", "11.9"),
    ]
}